// <auto-generated />
using System;
using CinemaNetwork.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaNetwork.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CinemaNetworkContext))]
    partial class CinemaNetworkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.AgeRestriction", b =>
                {
                    b.Property<int>("AgeRestrictionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgeRestrictionsId"));

                    b.Property<int>("Restriction")
                        .HasColumnType("int")
                        .HasColumnName("AgeRestriction");

                    b.HasKey("AgeRestrictionsId");

                    b.ToTable("AgeRestrictions");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Check", b =>
                {
                    b.Property<int>("ChecksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChecksId"));

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("BuyTime")
                        .HasColumnType("time");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethodsId")
                        .HasColumnType("int");

                    b.Property<int>("Sum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ChecksId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PaymentMethodsId");

                    b.ToTable("Checks");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.CheckTicket", b =>
                {
                    b.Property<int>("CheckTicketsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckTicketsId"));

                    b.Property<int>("CheckId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("CheckTicketsId");

                    b.HasIndex("CheckId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("CheckTickets");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Cinema", b =>
                {
                    b.Property<int>("CinemasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CinemasId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Address");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CitiesId");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDateTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDateTime");

                    b.HasKey("CinemasId");

                    b.HasIndex("CityId");

                    b.ToTable("Cinemas");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.City", b =>
                {
                    b.Property<int>("CitiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitiesId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("City");

                    b.HasKey("CitiesId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Client", b =>
                {
                    b.Property<int>("ClientsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientsId"));

                    b.Property<string>("CellNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CellNumber");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDateTime");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Surname");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDateTime");

                    b.HasKey("ClientsId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Country", b =>
                {
                    b.Property<int>("CountriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountriesId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Country");

                    b.HasKey("CountriesId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Employee", b =>
                {
                    b.Property<int>("EmployeesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeesId"));

                    b.Property<string>("CellNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CellNumber");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int")
                        .HasColumnName("CinemaId");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDateTime");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Surname");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDateTime");

                    b.HasKey("EmployeesId");

                    b.HasIndex("CinemaId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Genre", b =>
                {
                    b.Property<int>("GenresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenresId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Genre");

                    b.HasKey("GenresId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Hall", b =>
                {
                    b.Property<int>("HallsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HallsId"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int")
                        .HasColumnName("CinemaId");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDateTime");

                    b.Property<int>("HallNumber")
                        .HasColumnType("int")
                        .HasColumnName("HallNumber");

                    b.Property<int?>("HallTechnologiesId")
                        .HasColumnType("int")
                        .HasColumnName("HallTechnologiesId");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDateTime");

                    b.HasKey("HallsId");

                    b.HasIndex("CinemaId");

                    b.HasIndex("HallTechnologiesId");

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.HallTechnology", b =>
                {
                    b.Property<int>("HallTechnologiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HallTechnologiesId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("HallTechnology");

                    b.HasKey("HallTechnologiesId");

                    b.ToTable("HallTechnologies");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Language", b =>
                {
                    b.Property<int>("LanguagesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguagesId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Language");

                    b.HasKey("LanguagesId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Movie", b =>
                {
                    b.Property<int>("MoviesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoviesId"));

                    b.Property<int>("AgeRestrictionsId")
                        .HasColumnType("int")
                        .HasColumnName("AgeRestrictionsId");

                    b.Property<int>("Budget")
                        .HasColumnType("int")
                        .HasColumnName("Budget");

                    b.Property<int>("CountriesId")
                        .HasColumnType("int")
                        .HasColumnName("CountriesId");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDateTime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<int>("LanguagesId")
                        .HasColumnType("int")
                        .HasColumnName("LanguagesId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<byte[]>("Poster")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Poster");

                    b.Property<int>("PublishersId")
                        .HasColumnType("int")
                        .HasColumnName("PublishersId");

                    b.Property<int>("Runtime")
                        .HasColumnType("int")
                        .HasColumnName("Runtime");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDateTime");

                    b.HasKey("MoviesId");

                    b.HasIndex("AgeRestrictionsId");

                    b.HasIndex("CountriesId");

                    b.HasIndex("LanguagesId");

                    b.HasIndex("PublishersId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.MovieGenre", b =>
                {
                    b.Property<int>("MoviesGenresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoviesGenresId"));

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("MoviesGenresId");

                    b.HasIndex("GenresId");

                    b.HasIndex("MoviesId");

                    b.ToTable("MoviesGenres");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.MoviePoster", b =>
                {
                    b.Property<int>("MoviePosterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoviePosterId"));

                    b.Property<byte[]>("BinaryImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("PosterFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MoviePosterId");

                    b.HasIndex("MovieId");

                    b.ToTable("MoviePosters");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodsId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PaymentMethod");

                    b.HasKey("PaymentMethodsId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Publisher", b =>
                {
                    b.Property<int>("PublishersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublishersId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Publisher");

                    b.HasKey("PublishersId");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Run", b =>
                {
                    b.Property<int>("RunsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RunsId"));

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDateTime");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("MovieId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDateTime");

                    b.HasKey("RunsId");

                    b.HasIndex("MovieId");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Screening", b =>
                {
                    b.Property<int>("ScreeningsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScreeningsId"));

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("HallsId")
                        .HasColumnType("int");

                    b.Property<int>("LanguagesId")
                        .HasColumnType("int");

                    b.Property<int>("RunsId")
                        .HasColumnType("int");

                    b.Property<int>("ScreeningFormatsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ScreeningsId");

                    b.HasIndex("HallsId");

                    b.HasIndex("LanguagesId");

                    b.HasIndex("RunsId");

                    b.HasIndex("ScreeningFormatsId");

                    b.ToTable("Screenings");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.ScreeningFormat", b =>
                {
                    b.Property<int>("ScreeningFormatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScreeningFormatsId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ScreeningFormat");

                    b.HasKey("ScreeningFormatsId");

                    b.ToTable("ScreeningFormats");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Seat", b =>
                {
                    b.Property<int>("SeatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatsId"));

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVipCategory")
                        .HasColumnType("bit");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SeatsId");

                    b.HasIndex("HallId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Ticket", b =>
                {
                    b.Property<int>("TicketsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketsId"));

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ScreeningsId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("TicketsId");

                    b.HasIndex("ScreeningsId");

                    b.HasIndex("SeatId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Check", b =>
                {
                    b.HasOne("CinemaNetwork.Infrastructure.Models.Client", "Clients")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaNetwork.Infrastructure.Models.Employee", "Employees")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaNetwork.Infrastructure.Models.PaymentMethod", "PaymentMethods")
                        .WithMany()
                        .HasForeignKey("PaymentMethodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clients");

                    b.Navigation("Employees");

                    b.Navigation("PaymentMethods");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.CheckTicket", b =>
                {
                    b.HasOne("CinemaNetwork.Infrastructure.Models.Check", "Checks")
                        .WithMany()
                        .HasForeignKey("CheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaNetwork.Infrastructure.Models.Ticket", "Tickets")
                        .WithOne()
                        .HasForeignKey("CinemaNetwork.Infrastructure.Models.CheckTicket", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checks");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Cinema", b =>
                {
                    b.HasOne("CinemaNetwork.Infrastructure.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Employee", b =>
                {
                    b.HasOne("CinemaNetwork.Infrastructure.Models.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Hall", b =>
                {
                    b.HasOne("CinemaNetwork.Infrastructure.Models.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaNetwork.Infrastructure.Models.HallTechnology", "HallTechnology")
                        .WithMany()
                        .HasForeignKey("HallTechnologiesId");

                    b.Navigation("Cinema");

                    b.Navigation("HallTechnology");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Movie", b =>
                {
                    b.HasOne("CinemaNetwork.Infrastructure.Models.AgeRestriction", "AgeRestriction")
                        .WithMany()
                        .HasForeignKey("AgeRestrictionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaNetwork.Infrastructure.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaNetwork.Infrastructure.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaNetwork.Infrastructure.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublishersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeRestriction");

                    b.Navigation("Country");

                    b.Navigation("Language");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.MovieGenre", b =>
                {
                    b.HasOne("CinemaNetwork.Infrastructure.Models.Genre", "Genres")
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaNetwork.Infrastructure.Models.Movie", "Movies")
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genres");

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.MoviePoster", b =>
                {
                    b.HasOne("CinemaNetwork.Infrastructure.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Run", b =>
                {
                    b.HasOne("CinemaNetwork.Infrastructure.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Screening", b =>
                {
                    b.HasOne("CinemaNetwork.Infrastructure.Models.Hall", "Halls")
                        .WithMany()
                        .HasForeignKey("HallsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaNetwork.Infrastructure.Models.Language", "Languages")
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CinemaNetwork.Infrastructure.Models.Run", "Runs")
                        .WithMany()
                        .HasForeignKey("RunsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaNetwork.Infrastructure.Models.ScreeningFormat", "ScreeningFormats")
                        .WithMany()
                        .HasForeignKey("ScreeningFormatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Halls");

                    b.Navigation("Languages");

                    b.Navigation("Runs");

                    b.Navigation("ScreeningFormats");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Seat", b =>
                {
                    b.HasOne("CinemaNetwork.Infrastructure.Models.Hall", "Halls")
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Halls");
                });

            modelBuilder.Entity("CinemaNetwork.Infrastructure.Models.Ticket", b =>
                {
                    b.HasOne("CinemaNetwork.Infrastructure.Models.Screening", "Screenings")
                        .WithMany()
                        .HasForeignKey("ScreeningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaNetwork.Infrastructure.Models.Seat", "Seats")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screenings");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
